In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
        'Age': [22, 25, 23, 21, 24],
        'Score': [85, 78, 92, None, 88],
        'City': ['Delhi', 'Mumbai', 'bangalore', 'Chennai', 'Delhi']}
df = pd.DataFrame(data)
print(df)

      Name  Age  Score       City
0    Alice   22   85.0      Delhi
1      Bob   25   78.0     Mumbai
2  Charlie   23   92.0  bangalore
3    Diana   21    NaN    Chennai
4      Eve   24   88.0      Delhi

# Adding Columns

In [4]:
df['Country'] = ['India'] * 5

In [5]:
df

      Name  Age  Score       City Country
0    Alice   22   85.0      Delhi   India
1      Bob   25   78.0     Mumbai   India
2  Charlie   23   92.0  bangalore   India
3    Diana   21    NaN    Chennai   India
4      Eve   24   88.0      Delhi   India

In [6]:
df['Bonus_Score'] = df['Score'] * 0.1

In [7]:
df

      Name  Age  Score       City Country  Bonus_Score
0    Alice   22   85.0      Delhi   India          8.5
1      Bob   25   78.0     Mumbai   India          7.8
2  Charlie   23   92.0  bangalore   India          9.2
3    Diana   21    NaN    Chennai   India          NaN
4      Eve   24   88.0      Delhi   India          8.8

In [8]:
df['Grade'] = np.where(df['Score'] >=85, 'A', 'B')

In [9]:
df

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22   85.0      Delhi   India          8.5     A
1      Bob   25   78.0     Mumbai   India          7.8     B
2  Charlie   23   92.0  bangalore   India          9.2     A
3    Diana   21    NaN    Chennai   India          NaN     B
4      Eve   24   88.0      Delhi   India          8.8     A

# Updating Values

In [10]:
df.loc[1, 'Age'] = 27

In [11]:
df

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22   85.0      Delhi   India          8.5     A
1      Bob   27   78.0     Mumbai   India          7.8     B
2  Charlie   23   92.0  bangalore   India          9.2     A
3    Diana   21    NaN    Chennai   India          NaN     B
4      Eve   24   88.0      Delhi   India          8.8     A

In [14]:
df.at[2, 'Age'] = 27

In [15]:
df

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22   85.0      Delhi   India          8.5     A
1      Bob   27   78.0     Mumbai   India          7.8     B
2  Charlie   27   92.0  bangalore   India          9.2     A
3    Diana   21    NaN    Chennai   India          NaN     B
4      Eve   24   88.0      Delhi   India          8.8     A

In [16]:
df['Score'] = df['Score'] +5

In [17]:
df

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22   90.0      Delhi   India          8.5     A
1      Bob   27   83.0     Mumbai   India          7.8     B
2  Charlie   27   97.0  bangalore   India          9.2     A
3    Diana   21    NaN    Chennai   India          NaN     B
4      Eve   24   93.0      Delhi   India          8.8     A

In [18]:
df['City'] = np.where(df['City'] == 'Delhi', 'NCR', df['City'])

In [19]:
df

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22   90.0        NCR   India          8.5     A
1      Bob   27   83.0     Mumbai   India          7.8     B
2  Charlie   27   97.0  bangalore   India          9.2     A
3    Diana   21    NaN    Chennai   India          NaN     B
4      Eve   24   93.0        NCR   India          8.8     A

# Removing Rows & Columns

In [20]:
df.drop([1,3], axis=0)

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22   90.0        NCR   India          8.5     A
2  Charlie   27   97.0  bangalore   India          9.2     A
4      Eve   24   93.0        NCR   India          8.8     A

In [21]:
df.drop(['Age', 'City'], axis=1)

      Name  Score Country  Bonus_Score Grade
0    Alice   90.0   India          8.5     A
1      Bob   83.0   India          7.8     B
2  Charlie   97.0   India          9.2     A
3    Diana    NaN   India          NaN     B
4      Eve   93.0   India          8.8     A

# Handling Missing Values

In [22]:
df.isnull().sum()

Name           0
Age            0
Score          1
City           0
Country        0
Bonus_Score    1
Grade          0
dtype: int64

In [24]:
mean_value = df['Score'].mean()
mean_value

np.float64(90.75)

In [25]:
df['Score'] = df['Score'].fillna(mean_value)

In [26]:
df

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22  90.00        NCR   India          8.5     A
1      Bob   27  83.00     Mumbai   India          7.8     B
2  Charlie   27  97.00  bangalore   India          9.2     A
3    Diana   21  90.75    Chennai   India          NaN     B
4      Eve   24  93.00        NCR   India          8.8     A

In [27]:
median_value = df['Score'].median()
median_value

np.float64(90.75)

In [29]:
df['Score'] = df['Score'].fillna(median_value)

In [30]:
df

      Name  Age  Score       City Country  Bonus_Score Grade
0    Alice   22  90.00        NCR   India          8.5     A
1      Bob   27  83.00     Mumbai   India          7.8     B
2  Charlie   27  97.00  bangalore   India          9.2     A
3    Diana   21  90.75    Chennai   India          NaN     B
4      Eve   24  93.00        NCR   India          8.8     A