In [35]:
import pandas as pd

# Series

In [36]:
data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64

In [37]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 45],
        'Salary': [50000, 60000, 70000, 80000, 90000],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
        'Education': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master']}
series = pd.Series(data)
print(series)

Name                  [Alice, Bob, Charlie, David, Eve]
Age                                [25, 30, 35, 40, 45]
Salary              [50000, 60000, 70000, 80000, 90000]
Department          [HR, IT, Finance, Marketing, Sales]
Education     [Bachelor, Master, PhD, Bachelor, Master]
dtype: object

# DataFrame

In [38]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 45],
        'Salary': [50000, 60000, 70000, 80000, 90000],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
        'Education': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master']}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary Department Education
0    Alice   25   50000         HR  Bachelor
1      Bob   30   60000         IT    Master
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master

# Some Basic Operations In Pandas

In [39]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Sam', 'Ironman', 'Joy'],
        'Age': [25, 30, 35, 40, 45, 42, 37, 43],
        'Salary': [50000, 60000, 70000, 80000, 90000, 100000, 85000, 95000],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'HR', 'Marketing', "IT"],
        'Education': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master', 'Master', 'Bachelor', 'CS']}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary Department Education
0    Alice   25   50000         HR  Bachelor
1      Bob   30   60000         IT    Master
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

In [40]:
df.head()  # prints 5 rows from the top

      Name  Age  Salary Department Education
0    Alice   25   50000         HR  Bachelor
1      Bob   30   60000         IT    Master
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master

In [41]:
df.head(3) # prints the number of rows you pass

      Name  Age  Salary Department Education
0    Alice   25   50000         HR  Bachelor
1      Bob   30   60000         IT    Master
2  Charlie   35   70000    Finance       PhD

In [42]:
df.tail()  # prints bottom 5 rows

      Name  Age  Salary Department Education
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

In [43]:
df.tail(4)  # prints the number of rows you passed from the bottom

      Name  Age  Salary Department Education
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

In [44]:
df

      Name  Age  Salary Department Education
0    Alice   25   50000         HR  Bachelor
1      Bob   30   60000         IT    Master
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

In [45]:
df[2:6]  # prints rows as [Start, End-1], if you want to see rows randomly

      Name  Age  Salary Department Education
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master

In [46]:
df.columns  # prints all the columns in the dataset

Index(['Name', 'Age', 'Salary', 'Department', 'Education'], dtype='object')

In [47]:
df.Name  # way to print any specific column

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5        Sam
6    Ironman
7        Joy
Name: Name, dtype: object

In [48]:
df[['Age', 'Name', 'Salary']]  # Accessing multiple columns together

   Age     Name  Salary
0   25    Alice   50000
1   30      Bob   60000
2   35  Charlie   70000
3   40    David   80000
4   45      Eve   90000
5   42      Sam  100000
6   37  Ironman   85000
7   43      Joy   95000

In [49]:
df['Salary'].max()  # printing maximum value of a column

np.int64(100000)

In [50]:
df['Salary'].min()  # printing minimum value of a column

np.int64(50000)

In [51]:
df['Salary'].mean()  # printing average of a column

np.float64(78750.0)

In [52]:
df['Salary'].std()  # printingstandard deviation of a column

np.float64(17474.471175321527)

In [53]:
df.describe()  # Getting statistical details of the dataset

             Age         Salary
count   8.000000       8.000000
mean   37.125000   78750.000000
std     6.875162   17474.471175
min    25.000000   50000.000000
25%    33.750000   67500.000000
50%    38.500000   82500.000000
75%    42.250000   91250.000000
max    45.000000  100000.000000

In [54]:
df

      Name  Age  Salary Department Education
0    Alice   25   50000         HR  Bachelor
1      Bob   30   60000         IT    Master
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

In [55]:
df[df.Salary > 60000] # applying a condition to filter rows

      Name  Age  Salary Department Education
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

In [56]:
df[df.Salary <= 60000]

    Name  Age  Salary Department Education
0  Alice   25   50000         HR  Bachelor
1    Bob   30   60000         IT    Master

In [57]:
df.info() # getting basic information about the dataset like, datatypes of the dataset, numer of rows and columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Age         8 non-null      int64
 2   Salary      8 non-null      int64
 3   Department  8 non-null      object
 4   Education   8 non-null      object
dtypes: int64(2), object(3)
memory usage: 452.0+ bytes

In [58]:
df.shape # get the number of rows and columns in the dataset

(8, 5)

In [59]:
df.index # get the index of the dataset

RangeIndex(start=0, stop=8, step=1)

In [60]:
df.set_index('Name', inplace=True)  # change the index as your desired column

In [61]:
df

         Age  Salary Department Education
Name
Alice     25   50000         HR  Bachelor
Bob       30   60000         IT    Master
Charlie   35   70000    Finance       PhD
David     40   80000  Marketing  Bachelor
Eve       45   90000      Sales    Master
Sam       42  100000         HR    Master
Ironman   37   85000  Marketing  Bachelor
Joy       43   95000         IT        CS

In [62]:
df.loc['David']  # accessing information of a specific data point

Age                  40
Salary            80000
Department    Marketing
Education      Bachelor
Name: David, dtype: object

In [63]:
df.reset_index(inplace=True)  # reset index as it was before

In [64]:
df

      Name  Age  Salary Department Education
0    Alice   25   50000         HR  Bachelor
1      Bob   30   60000         IT    Master
2  Charlie   35   70000    Finance       PhD
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

# Combining Multiple Conditions

In [65]:
filter_data = df[(df['Age']>35) & (df['Salary']>50000)]  # combining multiple conditions using and (&), or (|)

In [66]:
filter_data

      Name  Age  Salary Department Education
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS

In [67]:
filter_data = df[(df['Age']>35) | (df['Salary']>70000)]

In [68]:
filter_data

      Name  Age  Salary Department Education
3    David   40   80000  Marketing  Bachelor
4      Eve   45   90000      Sales    Master
5      Sam   42  100000         HR    Master
6  Ironman   37   85000  Marketing  Bachelor
7      Joy   43   95000         IT        CS