In [2]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd
import numpy as np

# Sample sales dataset
data = {
    'region':  ['North', 'South', 'North', 'East', 'South', 'East'],
    'product': ['A', 'B', 'B', 'A', 'A', 'B'],
    'sales':   [200, 150, np.nan, 300, np.nan, 180],
    'units':   [10, 8, 12, 15, 7, 9],
}

df = pd.DataFrame(data)
print(df)

  region product  sales  units
0  North       A  200.0     10
1  South       B  150.0      8
2  North       B    NaN     12
3   East       A  300.0     15
4  South       A    NaN      7
5   East       B  180.0      9

# Interpolation

In [11]:
df['sales_linear'] = df['sales'].interpolate(method='linear')
df[['sales', 'sales_linear']]

   sales  sales_linear
0  200.0         200.0
1  150.0         150.0
2    NaN         225.0
3  300.0         300.0
4    NaN         240.0
5  180.0         180.0

In [10]:
df['sales_polynomial'] = df['sales'].interpolate(method='polynomial', order=2)
df['sales_polynomial']

0    200.000000
1    150.000000
2    218.823529
3    300.000000
4    287.058824
5    180.000000
Name: sales_polynomial, dtype: float64

In [6]:
df['sales'].interpolate(method='nearest')

0    200.0
1    150.0
2    150.0
3    300.0
4    300.0
5    180.0
Name: sales, dtype: float64

# Sorting

In [12]:
df

  region product  sales  units  sales_linear  sales_polynomial
0  North       A  200.0     10         200.0        200.000000
1  South       B  150.0      8         150.0        150.000000
2  North       B    NaN     12         225.0        218.823529
3   East       A  300.0     15         300.0        300.000000
4  South       A    NaN      7         240.0        287.058824
5   East       B  180.0      9         180.0        180.000000

In [16]:
sorted_df = df.sort_values(by='units', ascending=False)
sorted_df

  region product  sales  units  sales_linear  sales_polynomial
3   East       A  300.0     15         300.0        300.000000
2  North       B    NaN     12         225.0        218.823529
0  North       A  200.0     10         200.0        200.000000
5   East       B  180.0      9         180.0        180.000000
1  South       B  150.0      8         150.0        150.000000
4  South       A    NaN      7         240.0        287.058824

In [18]:
df_sorted = df.sort_values(by='units', ascending=False)
print(df_sorted[['region', 'product', 'units']])

  region product  units
3   East       A     15
2  North       B     12
0  North       A     10
5   East       B      9
1  South       B      8
4  South       A      7

In [21]:
multi_sorted = df.sort_values(by=['region','units'], ascending=[True,False])
print(multi_sorted[['region','units']])

  region  units
3   East     15
5   East      9
2  North     12
0  North     10
1  South      8
4  South      7

In [22]:
df.sort_values(by='sales', na_position='first')

  region product  sales  units  sales_linear  sales_polynomial
2  North       B    NaN     12         225.0        218.823529
4  South       A    NaN      7         240.0        287.058824
1  South       B  150.0      8         150.0        150.000000
5   East       B  180.0      9         180.0        180.000000
0  North       A  200.0     10         200.0        200.000000
3   East       A  300.0     15         300.0        300.000000

In [23]:
df.sort_values(by='sales', na_position='last')

  region product  sales  units  sales_linear  sales_polynomial
1  South       B  150.0      8         150.0        150.000000
5   East       B  180.0      9         180.0        180.000000
0  North       A  200.0     10         200.0        200.000000
3   East       A  300.0     15         300.0        300.000000
2  North       B    NaN     12         225.0        218.823529
4  South       A    NaN      7         240.0        287.058824

In [24]:
shuffled = df.sample(frac=1)
restored = shuffled.sort_index()
restored

  region product  sales  units  sales_linear  sales_polynomial
0  North       A  200.0     10         200.0        200.000000
1  South       B  150.0      8         150.0        150.000000
2  North       B    NaN     12         225.0        218.823529
3   East       A  300.0     15         300.0        300.000000
4  South       A    NaN      7         240.0        287.058824
5   East       B  180.0      9         180.0        180.000000

# Aggregation

In [26]:
print('Sum :', df['units'].sum())

Sum : 61

In [27]:
print('mean :', df['units'].mean())

mean : 10.166666666666666

In [28]:
print('Median :', df['units'].median())

Median : 9.5

In [30]:
stats_summary = df['units'].agg(['sum', 'mean', 'median', 'std', 'min', 'max'])
stats_summary

sum       61.000000
mean      10.166667
median     9.500000
std        2.926887
min        7.000000
max       15.000000
Name: units, dtype: float64

In [31]:
df.describe()

       sales      units  sales_linear  sales_polynomial
count    4.0   6.000000      6.000000          6.000000
mean   207.5  10.166667    215.833333        222.647059
std     65.0   2.926887     52.193550         59.592329
min    150.0   7.000000    150.000000        150.000000
25%    172.5   8.250000    185.000000        185.000000
50%    190.0   9.500000    212.500000        209.411765
75%    225.0  11.500000    236.250000        270.000000
max    300.0  15.000000    300.000000        300.000000

In [32]:
diff_columns = df.agg({
    'sales': ['sum', 'mean'],
    'units': ['min', 'max']
})

In [33]:
diff_columns

      sales  units
sum   830.0    NaN
mean  207.5    NaN
min     NaN    7.0
max     NaN   15.0

In [34]:
df

  region product  sales  units  sales_linear  sales_polynomial
0  North       A  200.0     10         200.0        200.000000
1  South       B  150.0      8         150.0        150.000000
2  North       B    NaN     12         225.0        218.823529
3   East       A  300.0     15         300.0        300.000000
4  South       A    NaN      7         240.0        287.058824
5   East       B  180.0      9         180.0        180.000000

# GroupBy

In [36]:
region_total = df.groupby('region')['units'].sum()
region_total

region
East     24
North    22
South    15
Name: units, dtype: int64

In [38]:
grouped = df.groupby(['region', 'product'])['units'].sum()
grouped

region  product
East    A          15
        B           9
North   A          10
        B          12
South   A           7
        B           8
Name: units, dtype: int64

In [39]:
result = df.groupby('region').agg(
    total_units = ('units', 'sum'),
    avg_sale = ('sales', 'mean'),
    pro_count = ('product', 'count')
)

In [40]:
result

        total_units  avg_sale  pro_count
region
East             24     240.0          2
North            22     200.0          2
South            15     150.0          2